### ISSUE TITLE
HTMLSelectElement.prototype.remove not remove dom Element

### ISSUE THREAD

**Issue by anthony-redFox** [WebReflection/dom4#19] opened 2015-07-24 11:48 UTC
The remove() method is used to remove an option from a drop-down list and IE requires option index.

Please review my pull Request!

**Comment by WebReflection** [comment] 2015-07-24 15:51
OK, thanks for the PR but I don't really fancy it, here the reason:

  * you are not doing any feature detection, whatever IE needs here seems to be very obtrusive for every other browser too
  * you are attaching non standard methods to the prototype ... not needed and obtrusive. You can just use the dom4 scope to eventually trap that method and use call/apply without needing to attach it with the `native` prefix
  * you are checking the argument, not checking that `this` points to an instanceof Select, there are hidden potential errors in this patch
  * the test changes another one, you could just create a new one specific for this select problem, instead of changing one that was testing other nodes

Last, but not least, I'd like to understand with a basic HTML example which case, and also **which IE** will fail through `remove`

Thanks for improving this PR or for telling me more about the issue.

Best Regards

**Comment by QiV** [comment] 2015-07-24 21:34
It is not IE specific problem. I posted this bug at 2013 https://www.w3.org/Bugs/Public/show_bug.cgi?id=20720
The problem will be somewhere here:
```
while( node.firstChild ) {
  node.firstChild.remove();
}
```
for the most developers this code will be clearing node from others nodes like `node.innerHTML = ''`, but if there will be a select node, it will never stops - node.firstChild.remove() will not lead to node.firstChild removal... just unexpected behavior.

**Comment by WebReflection** [comment] 2015-07-26 14:21
this has been fixed in `1.4.8` in a different way, obtaining same result ;-)

Thanks

**Closed by WebReflection** 2015-07-26 14:21 UTC
